### ISSUE TITLE
Upgrade Energi Core Node binary in Monitor image/container to version 3.1.0

### ISSUE THREAD

**Issue by eandersons** [eandersons/energi-docker-compose#14]

**Comment by Vulpecula-nl** [comment]
This is why I keep getting warning messages in my discord server?

**Comment by eandersons** [comment]
Yes, exactly.

**Comment by eandersons** [comment]
Issue was resolved with the commit 50d4d81.

To update the Energi Core Node Monitor image and container the following command should be executed: `./e3dc update monitor`.

**Comment by Vulpecula-nl** [comment]
Thank you, getting no warnings anymore in my Discord server
