### ISSUE TITLE
Upgrade required messages but there is no upgrade

### ISSUE THREAD

**Issue by Vulpecula-nl** [eandersons/energi-docker-compose#17]
Getting discord messages that i have to upgrade but there is no upgrade. What do i need to do to stop the warning messages?

**Comment by eandersons** [comment]
I am receiving the same warning messages. I took a quick look but I could not spot a cause for this. Maybe some URL that is used in `nodemon.sh` to detect the current Energi version has been changed.

I will investigate more as soon as I will have a free time to do this.

**Comment by Vulpecula-nl** [comment]
There was a messages about this on the discord server. 

“ There is no new upgrade required. If you are getting notifications through Node monitor, follow the next steps to fix it:
Re-run the following as nrgstaker to upgrade local nodemon:

`bash -ic "$(wget -4qO- -o- raw.githubusercontent.com/energicryptocurrency/energi3-provisioning/master/scripts/linux/nodemon.sh)" ; source ~/.bashrc`

Take all the default values when prompted.”

Maybe this helps?

**Comment by eandersons** [comment]
This will not help as `nodemon.sh` in this project has additional and modified code to run it in a Docker container and its content differs from <https://raw.githubusercontent.com/energicryptocurrency/energi3-provisioning/master/scripts/linux/nodemon.sh>.

I see that the original `nodemon.sh` was recently updated (I am subscribed to all activity notifications for `energi3-provisioning` repository but I do not recall receiving one): https://github.com/energicryptocurrency/energi3-provisioning/commit/18765114989280a5bac49c5816e7a04fd5effaf6.

I am planning to integrate `nodemon.sh` changes into this repository tomorrow morning.

**Comment by Vulpecula-nl** [comment]
I have created a pull request. The update is not something special. Its just a change for the git repo. I have copied all the changes from https://github.com/energicryptocurrency/energi3-provisioning/commit/18765114989280a5bac49c5816e7a04fd5effaf6

I have tested it too. Its working, i don't get any warning messages anymore.
