### ISSUE TITLE
Still getting Permission denied (publickey) messages

### ISSUE THREAD

**Issue by Vulpecula-nl** [eandersons/energi-docker-compose#31]
Im still getting nrgstaker@core: Permission denied (publickey) messages. I'm running your latest commits. I have done all you said below and all the files are there. But still see no uptime from the core container

> Container name is right. In Docker network each container is accessible with the alias that is the same as the name of service defined in `docker-compose.yml` (and `docker-compose.override.yml`) - `core` and `monitor` respectively.
> 
> I have rebuilt images and recreated containers multiple times since changes that introduced SSH and I have not observed the error "Permission denied (publickey)". This one could be hard to debug. I have a couple of things in my mind that can be checked.
> 
> Is core node container running normally and without errors in container logs?
> 
> You can try to attach to the monitor container (`docker-compose exec monitor bash`) and check if the directory `~/.ssh` exists and it contains files `id_rsa`, `id_rsa.pub` and `config`. I suspect that those files will be there (at least `config`). If those files exist, then you can try `ssh -vT core`, and output may give some clues.
> 
> Another thing to check is if output of `docker-compose exec core ash -c 'cat ~/.sshd/authorized_keys'` is the same as of `docker-compose exec monitor bash -c 'cat ~/.ssh/id_rsa.pub'`.
> 
> If some files are missing or output of the last two commands differs, then the following commands should fix the issue: `docker-compose build`, then `docker-compose up --detach --force-recreate`.

Out come of `ssh -vT core`, have replaced the SHA256 keys with XXX
nrgstaker@6a728ca65830:~$ ssh -vT core
OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/nrgstaker/.ssh/config
debug1: /home/nrgstaker/.ssh/config line 1: Applying options for core
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to core [192.168.48.2] port 2222.
debug1: Connection established.
debug1: identity file /home/nrgstaker/.ssh/id_rsa type 0
debug1: identity file /home/nrgstaker/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.3
debug1: match: OpenSSH_8.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to core:2222 as 'nrgstaker'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:XXX
debug1: checking without port identifier
Warning: Permanently added '[core]:2222' (RSA) to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/nrgstaker/.ssh/id_rsa RSA SHA256:XXX explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/nrgstaker/.ssh/id_rsa RSA SHA256:XXX+w explicit
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
nrgstaker@core: Permission denied (publickey).

**Comment by Vulpecula-nl** [comment]
After some research i have found the solution to this issue. It turns out to be a permission issue on the file `authorized_keys` file. Permissions needs to be 0600. I found this on [this amazon page](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-fix-permission-denied-errors/). After changing the permissions and restarting the core container, the error is gone. This needs to be applied on the image, but don't know what the best option is. @eandersons Could you fix it? Thanks

**Comment by eandersons** [comment]
Well, this is somewhat strange as Docker containers are supposed to work the same on different machines. On both my development computer (Arch) and home server (Debian) `.sshd/authorized_keys` had permissions `644` in the Core container and everything was working fine.
Just out of curiosity - what operating system are you running Energi Core Node and Monitor containers on?

Anyway, I have updated `Dockerfile` in ba59db2 to set permissions `600` for `.sshd/authorized_keys`.
To update Energi Core Node container: `./helper update core`.

**Comment by Vulpecula-nl** [comment]
My home server is Ubuntu 21.04.
