### ISSUE TITLE
Getting the following errors after updating to new release

### ISSUE THREAD

**Issue by Vulpecula-nl** [eandersons/energi-docker-compose#42]
Getting two errors after updating. 

This error is in the container log.

```
panic: interface conversion: interface {} is nil, not *types.Block
goroutine 1 [running]:
github.com/energicryptocurrency/energi/core.(*BlockChain).CurrentBlock(...)
	/energi/core/blockchain.go:378
```
And this error when I use the `helper` script

`./helper: 122: arithmetic expression: expecting primary: " "0" + "0" "`

Can you help me solving this again? @eandersons

**Comment by eandersons** [comment]
I will try to look into it in the next couple of days.

Do these errors cause the container to be unusable?

@Vulpecula-nl, could you please provide exact steps you executed before getting these errors?

**Comment by Vulpecula-nl** [comment]
@eandersons i have tried starting the container by `docker-compose up -d` but also with `./helper start`

Getting the first error every minute in the log of the container.

**Comment by eandersons** [comment]
Unfortunately I was not able to reproduce the panic error. Both core and monitor containers are working fine on my server and development environment.

@Vulpecula-nl, could you please provide log records from the container start till the first occurrence of the error?
Either view logs with `docker compose logs [core | monitor]` or remove and then start containers without the option `--detach` (`-d`) and copy the output.

In the meantime you could try to rebuild images: `docker compose build --no-cache && docker compose up --detach`. There is a tiny chance that this will resolve the issue.

---

> `./helper: 122: arithmetic expression: expecting primary: " "0" + "0" "`

What command did you execute when this error happened?

**Comment by Vulpecula-nl** [comment]
I have removed the whole directory that i cloned before and removed the volume and image from my docker instance. 

Now i have cloned your git repository again, moved all the files in the correct directory and ran the setup again, but keep getting and error on a `mv` command 

Here the complete output:
```
vulpecula@docker-server:~/energi-docker-compose$ ./helper setup
Creating network "energi_default" with the default driver
Creating volume "energi_core-data" with default driver
Creating energi_core_run ... done
mv: can't rename '/setup/.energi_core/keystore/*': No such file or directory
Creating energi_core_run ... done
INFO [03-07|18:47:14.548] Maximum peer count                       ETH=25 LES=0 total=25
ERROR[03-07|18:47:14.549] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-07|18:47:14.549] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-07|18:47:14.549] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-07|18:47:14.549] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [03-07|18:47:14.556] Database doesn't exist, skipping         database=chaindata path=/home/nrgstaker/.energicore3/energi3/chaindata
INFO [03-07|18:47:14.556] Database doesn't exist, skipping         database=lightchaindata path=/home/nrgstaker/.energicore3/energi3/lightchaindata
.energicore3/energi3/chaindata/
.energicore3/energi3/chaindata/660848.ldb

```
---
> > `./helper: 122: arithmetic expression: expecting primary: " "0" + "0" "`
> 
> What command did you execute when this error happened?

See line 122 of the helper script. hint: bootstrap-chaindata

---
Edit: I see in the setup directory the directory .energicore3 needs to be renamed to .energi_core. But after renaming it myself, i still get the error `can't rename`, it looks like the whole /setup directory is missing inside the docker container when the setup is running.

**Comment by eandersons** [comment]
Sorry for getting back to you after so long time!

> `mv: can't rename '/setup/.energi_core/keystore/*': No such file or directory`

This means that the directory `setup/.energi_core/keystore` is empty. You should copy keystore file in it before using `./helper setup`, so the setup script could move it to the target directory within the core container.

I will try to update the setup script to print an additional message when the directory `setup/.energi_core/keystore` is empty.

**Comment by Vulpecula-nl** [comment]
I have copied the keystore file in there before running the setup script. But the whole setup folder is not present in the container to copy. Maybe because it wants to mount it in the root directory

**Comment by eandersons** [comment]
What `./helper setup` basically does is the following:

- it creates a temporary core container and mounts the local directory `setup` into into container as `/setup`;
- then the setup script tries to move everything from `/setup/.energi_core/keystore` to `/home/nrgstaker/.energi_core/keystore`.

To make sure what really happens in the setup container, you could modify `setup/setup.sh` by adding the following lines (or anything else that will help you to inspect what is going on) before the command `mkdir`:

```
ls -ahl /setup
ls -ahl /setup/.energi_core
ls -ahl /setup/.energi_core/keystore
```

and then execute `./helper setup` to see what really is in the setup container's directory `/setup`.

In the meantime I spotted another issue: setup is not using the correct directory - it is using `/home/nrgstaker/.energicore3` instead of `/home/nrgstaker/.energi_core`. I will fix it right away.

**Comment by eandersons** [comment]
> I have removed the whole directory that i cloned before and removed the volume and image from my docker instance.

A side note: usually there is no need to remove volumes, especially when it takes really long time to synchronize the blockchain.

**Comment by Vulpecula-nl** [comment]
> > I have removed the whole directory that i cloned before and removed the volume and image from my docker instance.
> 
> A side note: usually there is no need to remove volumes, especially when it takes really long time to synchronize the blockchain.

Yeah I know, but had messed around in the container, so thought its better to create it from scratch. 



> What `./helper setup` basically does is the following:
> 
> * it creates a temporary core container and mounts the local directory `setup` into into container as `/setup`;
> * then the setup script tries to move everything from `/setup/.energi_core/keystore` to `/home/nrgstaker/.energi_core/keystore`.
> 
> To make sure what really happens in the setup container, you could modify `setup/setup.sh` by adding the following lines (or anything else that will help you to inspect what is going on) before the command `mkdir`:
> 
> ```
> ls -ahl /setup
> ls -ahl /setup/.energi_core
> ls -ahl /setup/.energi_core/keystore
> ```
> 
> and then execute `./helper setup` to see what really is in the setup container's directory `/setup`.
> 
> In the meantime I spotted another issue: setup is not using the correct directory - it is using `/home/nrgstaker/.energicore3` instead of `/home/nrgstaker/.energi_core`. I will fix it right away.

I did what you asked me to do to inspect, this is the output when running the setup again. So you can see that i have placed my keystore in the right directory, but it don;t want to copy it.

```
vulpecula@docker-server:~/energi-docker-compose$ ./helper setup
Creating energi_core_run ... done
total 20K    
drwxrwxr-x    3 nrgstake nrgstake    4.0K Mar 19 15:22 .
drwxr-xr-x    1 root     root        4.0K Mar 19 15:22 ..
drwxrwxr-x    3 nrgstake nrgstake    4.0K Mar  7 18:17 .energi_core
-rw-rw-r--    1 nrgstake nrgstake     458 Mar  7 18:17 README.md
-rw-rw-r--    1 nrgstake nrgstake     503 Mar 19 15:22 setup.sh
total 12K    
drwxrwxr-x    3 nrgstake nrgstake    4.0K Mar  7 18:17 .
drwxrwxr-x    3 nrgstake nrgstake    4.0K Mar 19 15:22 ..
drwxrwxr-x    2 nrgstake nrgstake    4.0K Mar  7 18:17 keystore
total 16K    
drwxrwxr-x    2 nrgstake nrgstake    4.0K Mar  7 18:17 .
drwxrwxr-x    3 nrgstake nrgstake    4.0K Mar  7 18:17 ..
-rw-rw-r--    1 nrgstake nrgstake      14 Mar  7 18:17 .gitignore
-rwxrwxr-x    1 nrgstake nrgstake     489 Mar  7 18:17 UTC--2020-06-24T09-53-26.450Z--547f992eaf2b41c4b11af6841720e4d89d54bfc4
mv: can't rename '/setup/.energi_core/keystore/*': No such file or directory
Creating energi_core_run ... done
INFO [03-19|15:22:36.553] Maximum peer count                       ETH=25 LES=0 total=25
ERROR[03-19|15:22:36.554] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-19|15:22:36.554] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-19|15:22:36.554] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[03-19|15:22:36.554] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [03-19|15:22:36.562] Database doesn't exist, skipping         database=chaindata path=/home/nrgstaker/.energicore3/energi3/chaindata
INFO [03-19|15:22:36.562] Database doesn't exist, skipping         database=lightchaindata path=/home/nrgstaker/.energicore3/energi3/lightchaindata
.energicore3/energi3/chaindata/
.energicore3/energi3/chaindata/660848.ldb
.energicore3/energi3/chaindata/751207.ldb
.energicore3/energi3/chaindata/581841.ldb

```

**Comment by Vulpecula-nl** [comment]
Well, it turns out to be a git pull issue. If I read the output completely I have had known that the pull request wasn't done correctly. It showed an error on a .gitignore file that couldn't be merged. After removing the .gitignore file, I could pull your repository correctly and the setup was executed successfully.

Sorry by the way

**Comment by eandersons** [comment]
> Well, it turns out to be a git pull issue. If I read the output completely I have had known that the pull request wasn't done correctly. It showed an error on a .gitignore file that couldn't be merged. After removing the .gitignore file, I could pull your repository correctly and the setup was executed successfully.
> 
> Sorry by the way

No worries! Without this issue I would not have spotted that renaming `.energicore3` to `.energi_core` messed up some things, among them blockchain data initialization as database still was initialized in the directory `/home/nrgstaker/.energicore3` instead of `.energi_core` (see the pull request #46).
