### ISSUE TITLE
Core Node monitor

### ISSUE THREAD

**Issue by eandersons** [eandersons/energi-docker-compose#5]
Integrate Energi Core Node monitor ([`nodemon.sh`](https://github.com/energicryptocurrency/energi3-provisioning/blob/master/scripts/linux/nodemon.sh), [`nodemon-report.sh`](https://github.com/energicryptocurrency/energi3-provisioning/blob/master/scripts/linux/nodemon-report.sh) and [`nodemon-resync.sh`](https://github.com/energicryptocurrency/energi3-provisioning/blob/master/scripts/linux/nodemon-resync.sh)) to receive notifications about balance changes and to get other functionality provided by those scripts.

**Comment by Vulpecula-nl** [comment]
Is it difficult to add the Node monitor? I was looking in to it, but i see there is no option to add the Discord webhook tokens in the config file.

**Comment by eandersons** [comment]
Currently I do not know how difficult would be to add the Node Monitor. I am planning to integrate it into `energi3-docker-compose` in near future (could be a couple of months) as at least once a month (at least for me) syncing goes sideways and currently I am checking the Core Node manually twice a day.

Theoretically tokens could be added by specifying secrets or environment variables in `docker-compose.override.yml` and then the node monitor script could be run manually, but I am not sure if it will work on the container which is based on Alpine as, if I recall correctly, the installation script is created for Ubuntu, so most probably it might need adjustments.

---

I just checked [Energi 3 provisioning scripts](https://github.com/energicryptocurrency/energi3-provisioning/tree/master/scripts/linux) and they indeed are Ubuntu specific. That means they will not work on the Core Node container, so I think that the easiest way would be to create a helper container for Node Monitor based on Ubuntu image and to share the necessary volumes between Core and Monitor services.

**Comment by eandersons** [comment]
Energi Core Node Monitor was added with the commit e3a8cbb.

**Comment by Vulpecula-nl** [comment]
Thank you. I have updated my docker container and it all works at the first try.

**Comment by eandersons** [comment]
You are welcome! I am glad to read that.
