### ISSUE TITLE
Getting no information in my Discord server

### ISSUE THREAD

**Issue by Vulpecula-nl** [eandersons/energi-docker-compose#9]
I have been rewarded with a stake a few hours ago, but i did not get any message in my discord server. After the test messages I still haven't got any message. Is there something wrong with my container? When I look in the log of the container I can find one error. 
Error: near "rkhunter": syntax error

That is the whole error message.

**Comment by eandersons** [comment]
I could not spot any syntax errors around lines that contain `rkhunter`.

You could try the following to see if messages can still be sent to Discord:

- connect to the core container: `docker-compose exec --user=root monitor bash`;
- install `nano` or any other text editor: `apt install nano`;
- edit `nodemon.sh`:
  - `nano nodemon.sh`;
  - add the following code right before the line that contains `if [[ "${arg1}" == 'node_run' ]]` near the end of file:

    ```shell

      if [[ "${arg1}" == 'success_test' ]]
      then
        SEND_SUCCESS 'Success test message'
    
        exit 0
      fi
    
    ```
  - save and exit: `ctrl` + `S` and `ctrl` + `X`;
- send the test message: `bash nodemon.sh success_test`.

If the message will be successfully sent, then it seems that we will have to wait till I get the next reward to see if the success message will be sent, but I suspect that more adjustments would be necessary for `nodemon.sh`.

If the test message is not sent, then you could try to rebuild and recreate Energi Core Node Monitor image and container: `./e3dc update monitor` and then try to add the test code and send the test message again.

**Comment by Vulpecula-nl** [comment]
i have tested your modification and i can see the success test message appear in Discord

**Comment by eandersons** [comment]
I made an adjustment that might resolve the issue why the message about staking reward was not sent to Discord. I will try to push changes tomorrow.

**Comment by eandersons** [comment]
1c3b486 possibly fixes the issue why staking reward success message was not sent.

Turns out that some other message types were not sent as well.

To get changes and update the Energi Core Node Monitor container: `./e3dc update monitor` (or `git pull && ./e3dc update monitor` if `e3dc` is not yet pulled).

> A note on uptime value in informational messages. As originally `nodemon.sh` is intended to run on the same server as Energi Core Node, then uptime value is meant to be the uptime of Core. In `energi3-docker-compose` this value is the uptime of the cron process in the Energi Core Node Monitor container as Core and Monitor run in separate Docker containers.

I am planning to display both Core and Monitor uptime in informational messages if it will not require too much hassle and changes (see #10).

**Comment by Vulpecula-nl** [comment]
I have upgraded with your fix. As soon as i get a message in Discord i'll let you know. Thanks for the quick response.

[edit] i can confirm that i now getting messages in my Discord server. Thanks!
